export const data = [
  { id: 1, name: 'john' },
  { id: 2, name: 'peter' },
  { id: 3, name: 'susan' },
  { id: 4, name: 'anna' },
  { id: 5, name: 'john' },
  { id: 6, name: 'peter' },
  { id: 7, name: 'susan' },
  { id: 8, name: 'anna' },
  { id: 9, name: 'john' },
  { id: 10, name: 'peter' },
  { id: 11, name: 'susan' },
  { id: 12, name: 'anna' },
  { id: 13, name: 'john' },
  { id: 14, name: 'peter' },
  { id: 15, name: 'susan' },
  { id: 16, name: 'anna' },
];
